//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_NewSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose NewAction1
        {
            get
            {
                return SteamVR_Actions.newSet_NewAction1;
            }
        }
        
        public virtual SteamVR_Action_Boolean rightconcl
        {
            get
            {
                return SteamVR_Actions.newSet_rightconcl;
            }
        }
        
        public virtual SteamVR_Action_Pose righthandplace
        {
            get
            {
                return SteamVR_Actions.newSet_righthandplace;
            }
        }
        
        public virtual SteamVR_Action_Pose NewAction2waist
        {
            get
            {
                return SteamVR_Actions.newSet_NewAction2waist;
            }
        }
    }
}
